### ISSUE TITLE
Minor error in Badges and Schedules Lab

### ISSUE THREAD

**Issue by gabygalv** [learn-co-curriculum/python-p3-badges-and-schedules-lab#2]
### Canvas Link

https://learning.flatironschool.com/courses/6266/assignments/232406?module_item_id=544759

### Concern

Canvas needs a slight update in the instructions for assign_rooms(). The repo ReadMe and tests expect rooms 1-8 to be available but the canvas instructions specify we have rooms 1-7 available.

**Comment by professor-ben** [comment]
Thanks for the report! Working on a fix now.
