### ISSUE TITLE
Test takes 8 people but there's only supposed to be 7 rooms.

### ISSUE THREAD

**Issue by WAB0003** [learn-co-curriculum/python-p3-badges-and-schedules-lab#3]
### Canvas Link

https://learning.flatironschool.com/courses/6274/assignments/236164?module_item_id=554055

### Concern

The assign_rooms() function in the lab specifically says that you have a total of 7 rooms. The code doesn't pass unless you use 8 rooms. Additionally, the test takes into account one argument having 8 people, however, does not take into account only 2 people.

**Comment by professor-ben** [comment]
Hi Bill,

This is now fixed to reflect 8 rooms.

Thanks,
Ben
