### ISSUE TITLE
typo error in test

### ISSUE THREAD

**Issue by laurenhalpert** [learn-co-curriculum/python-p3-badges-and-schedules-lab#4]
### Canvas Link

https://learning.flatironschool.com/courses/6200/assignments/231743?module_item_id=542621

### Concern

 in the conference_badges_test.py file, the test for function assign_rooms() says:

MESSAGES = [
        "Hello, Guido! You'll be assigned to room 1!", 
        "Hello, Edsger! You'll be assigned to room 2!", 
        "Hello, Ada! You'll be assigned to room 3!", 
        "Hello, Charles! You'll be assigned to room 4!", 
        "Hello, Alan! You'll be assigned to room 5!", 
        "Hello, Grace! You'll be assigned to room 6!", 
        "Hello, Linus! You'll be assigned to room 7!", 
        "Hello, Matz! You'll be assigned to room 1!"
    ]

but the last element in that MESSAGES list should be room 8

**Comment by professor-ben** [comment]
Thanks for the report! This is now fixed in main.

-Ben
